inherit_from: .rubocop_todo.yml

require:
  - rubocop-packaging

plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - 'gemfiles/**/*'
    - 'vendor/bundle/**/*'

RSpec/SpecFilePathFormat:
  CustomTransform:
    OmniAuth: omniauth

Style/NumericPredicate:
  Enabled: false
