name: Ruby specs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test:
    name: Specs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.3', '2.4', '2.5', '2.6', '2.7', '3.0', '3.1', '3.2', '3.3']
        channel: ['stable']

        include:
          - ruby-version: 'head'
            channel: 'experimental'

    continue-on-error: ${{ matrix.channel != 'stable' }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run specs
      run: bundle exec rake
